### ISSUE TITLE
Could you add web support to this project? Thank you! 您可以在这个项目中添加对于web的支持吗？谢谢！

### ISSUE THREAD

**Issue by hyy007** [yang-f/flutter_svg_provider#1]
As we know, the web of flutter has been updated to the beta version. At the same time, many developers like me are trying to add web support to the original project recently. However, the SVG image does not work on the web side. I have been looking for a way to load the SVG image on the web, but I cannot find a solution. So I want to ask you for help, thank you!

鉴于我们知道，flutter的web已经更新到beta版本了，同时很多像我一样的开发者最近也在尝试将原有的项目添加web支持，但是svg格式的图片却在web端是不生效的，我一直在寻找web加载svg图片的方式，但是找不到解决方案。所以想来向你求助，谢谢！

**Comment by yang-f** [comment]
I'm very glad someone used this library. Any questions now?

**Comment by StefanLobbenmeier** [comment]
The other svg library also does not support the web, but they posted this workaround: 
https://github.com/dnfield/flutter_svg/issues/173#issuecomment-611403899

I am sure @hyy007 could apply something similar to this.

**Comment by Liuzhiyang94** [comment]
You may try this.

`
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/svg.dart';

class PlatformSvg {
  static Widget asset(String assetName,
      {double width,
      double height,
      BoxFit fit = BoxFit.contain,
      Color color,
      alignment = Alignment.center,
      String semanticsLabel}) {
    if (kIsWeb) {
      return Image.network("/assets/$assetName",
          width: width,
          height: height,
          fit: fit,
          color: color,
          alignment: alignment,
          semanticLabel: semanticsLabel);
    }
    return SvgPicture.asset(assetName,
        width: width,
        height: height,
        fit: fit,
        color: color,
        alignment: alignment,
        semanticsLabel: semanticsLabel);
  }
}`

**Comment by Liuzhiyang94** [comment]
You may try this.

https://github.com/dnfield/flutter_svg/issues/173#issuecomment-611403899
