### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by ximenqing183** [yang-f/flutter_svg_provider#24]
Launching lib\main.dart on JNY AL10 in debug mode...
lib\main.dart:1
/D:/env/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_svg-0.23.0+1/lib/svg.dart:325:5: Error: Type 'AssetBundle' not found.
    AssetBundle? bundle,
    ^^^^^^^^^^^
/D:/env/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_svg-0.23.0+1/lib/svg.dart:325:5: Error: 'AssetBundle' isn't a type.
    AssetBundle? bundle,
    ^^^^^^^^^^^
2

FAILURE: Build failed with an exception.

* Where:
Script 'D:\env\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\env\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by ximenqing183** [comment]
pubspec.yml 
 environment:
  sdk: ">=2.12.0 <3.0.0"
 ...
flutter_svg_provider: ^0.1.11

**Comment by yang-f** [comment]
https://github.com/dnfield/flutter_svg/issues/610
