### ISSUE TITLE
flutter 3.16 not working

### ISSUE THREAD

**Issue by FredrikBorgstrom** [yang-f/flutter_svg_provider#51]
After upgrading to Flutter 3.16 I can't get any images created with the Svg constructor to display.

**Comment by masterwok** [comment]
I'm also seeing this issue with assets failing to load via the `Svg` constructor after upgrading to Flutter `3.16`.

**Comment by arigilder** [comment]
Created PR https://github.com/yang-f/flutter_svg_provider/pull/53

**Comment by GuvanchBayryyyev** [comment]
Is this will be resolved?

**Comment by itb55ru** [comment]
I temporary changed in flutter_svg_provider.dart

`  ImageStreamCompleter load(SvgImageKey key, nil) {`
to  
`  ImageStreamCompleter loadBuffer(SvgImageKey key, nil) {`

**Comment by GuvanchBayryyyev** [comment]
> Created PR #53

```  flutter_svg_provider:
    git:
      url: https://github.com/yang-f/flutter_svg_provider.git
      ref: 3c153f3068309401f6e1436ce5768b3ddc77dca1
```
This should work for now

**Comment by progressify** [comment]
I have used this syntax in my `pubspec.yml`:

```
  flutter_svg_provider:
    git:
      url: https://github.com/arigilder/flutter_svg_provider
      ref: patch-1
```

It works good, I hope the PR will merged soon

**Comment by j-q-in-berlin** [comment]
When will the package containing this fix be published and available via pub.dev? Thank you! :)

**Comment by yang-f** [comment]
> When will the package containing this fix be published and available via pub.dev? Thank you! :)

done

**Comment by j-q-in-berlin** [comment]
Cool! Thanks! :)
