### ISSUE TITLE
Blurred SVG problem

### ISSUE THREAD

**Issue by ahmetveysels** [yang-f/flutter_svg_provider#62]
Is there a process here to convert the SVG file to an image file. Because in some SVG files the image is blurred.

**Comment by MikeGagarin** [comment]
HI! Were you able to fix this? If yes, please advise

**Comment by ahmetveysels** [comment]
> HI! Were you able to fix this? If yes, please advise

I used the [avs_svg_provider](https://pub.dev/packages/avs_svg_provider) package. when you enter scale or width - height in it, it gains clarity.

**Happy coding.**
